definitions:
  image_defaults: &image_defaults
    working_directory: ~/repo
    docker:
      - image: circleci/node:lts
        environment:
          TERM: xterm

version: 2
jobs:
  merge: 
    <<: *image_defaults
    steps:
      - run: echo success && exit 1

  release:
    <<: *image_defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install
      - run: npm run bootstrap
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run release

workflows:
  version: 2
  merge:
    jobs:
      - merge
      
  weekly_release:
    triggers:
      - schedule:
          cron: "30 5 * * 5"
          filters:
            branches:
              only:
                - master
    jobs:
      - release
