definitions:
  image_defaults: &image_defaults
    working_directory: ~/repo
    docker:
      - image: circleci/node:lts
        environment:
          TERM: xterm

version: 2
jobs:
  merge: 
    <<: *image_defaults
    steps:
      - run: echo success && exit 0

  release:
    <<: *image_defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install
      - run: npm run bootstrap
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - add_ssh_keys:
          fingerprints:
            - "14:e1:b6:2d:f2:c6:e6:db:98:53:d9:56:3b:e2:ca:97"
      - run:
          name: Configure git defaults
          command: git config user.email $GH_EMAIL && git config user.name $GH_USER
      - run: echo "registry=https://registry.npmjs.org" > ~/.npmrc
      - run: echo "registry \"https://registry.npmjs.org\"" > ~/.yarnrc
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: git status
      - run:
          name: Publish Releases
          command: npm run release

workflows:
  version: 2
  merge:
    jobs:
      - merge

  weekly_release:
    triggers:
      - schedule:
          cron: "30 5 * * 5"
          filters:
            branches:
              only:
                - master
    jobs:
      - release
